import { Colors } from 'discord.js';

export const ignoreRole = ['�️PRINCIPAL', 'admin-server'];
export const ignoreCategory = [
  'ignorecategory',
  'advertisements',
  'ɢᴇɴᴇʀᴀʟ-ʀᴜʟᴇꜱ',
  'admins-only',
  '👋・welcome',
  'forum-discussion',
  '🚀✨・𝐵𝒰𝑀𝒫',
  '🐧github',
  '📹pictures',
  'La Chambre des Secrets',
];

interface LanguageRoleType {
  name: string;
  color: number;
  unicodeEmoji: string;
  hoist: boolean;
  mentionable: boolean;
  room?: string[];
  hasCategory: boolean;
  haveAccessAllVoiceChanel?: Boolean;
}

export const languagesRoles: LanguageRoleType[] = [
  // language role

  {
    name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ',
    color: Colors.Blue,
    unicodeEmoji: ':tamazight_flag:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },

  {
    name: 'français',
    color: Colors.Blue,
    unicodeEmoji: ':flag_fr:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'english',
    color: Colors.Red,
    unicodeEmoji: ':flag_gb:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'dutch',
    color: Colors.Orange,
    unicodeEmoji: ':flag_nl:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'español',
    color: Colors.Red,
    unicodeEmoji: ':flag_es:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'deutsch',
    color: Colors.DarkRed,
    unicodeEmoji: ':flag_de:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'italiano',
    color: Colors.White,
    unicodeEmoji: ':flag_it:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'português',
    color: Colors.Green,
    unicodeEmoji: ':flag_pt:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'русский',
    color: Colors.Red,
    unicodeEmoji: ':flag_ru:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: '日本語',
    color: Colors.Red,
    unicodeEmoji: ':flag_jp:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: '中文',
    color: Colors.Gold,
    unicodeEmoji: ':flag_cn:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: '한국어',
    color: Colors.DarkBlue,
    unicodeEmoji: ':flag_kr:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'العربية',
    color: Colors.DarkGreen,
    unicodeEmoji: ':flag_sa:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'हिन्दी',
    color: Colors.Orange,
    unicodeEmoji: ':flag_in:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'ਪੰਜਾਬੀ',
    color: Colors.DarkOrange,
    unicodeEmoji: ':flag_pk:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'اردو',
    color: Colors.DarkGreen,
    unicodeEmoji: ':flag_pk:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'فارسی',
    color: Colors.Gold,
    unicodeEmoji: ':flag_ir:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'ไทย',
    color: Colors.DarkRed,
    unicodeEmoji: ':flag_th:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'tiếng Việt',
    color: Colors.DarkGreen,
    unicodeEmoji: ':flag_vn:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'Bahasa Indonesia',
    color: Colors.DarkAqua,
    unicodeEmoji: ':flag_id:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'Türkçe',
    color: Colors.Red,
    unicodeEmoji: ':flag_tr:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'עברית',
    color: Colors.DarkGold,
    unicodeEmoji: ':flag_il:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },

  // divertissement  roles

  {
    name: 'developer',
    color: Colors.Purple,
    unicodeEmoji: ':computer:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },

  {
    name: 'drawer',
    color: Colors.Gold,
    unicodeEmoji: ':art:',
    hoist: true,
    mentionable: true,
    room: ['Artist'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'DJ',
    color: Colors.Purple,
    unicodeEmoji: ':art:',
    hoist: true,
    mentionable: true,
    room: ['Artist'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'Artist',
    color: Colors.Purple,
    unicodeEmoji: ':art:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'memes',
    color: Colors.Yellow,
    unicodeEmoji: ':joy:',
    hoist: true,
    mentionable: true,
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },

  {
    name: 'photograph',
    color: Colors.Green,
    unicodeEmoji: ':mortar_board:',
    hoist: true,
    mentionable: true,
    room: ['Artist'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },

  {
    name: 'singer',
    color: Colors.Blue,
    unicodeEmoji: ':mortar_board:',
    hoist: true,
    mentionable: true,
    room: ['Artist'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },

  {
    name: 'student',
    color: Colors.Blue,
    unicodeEmoji: ':mortar_board:',
    hoist: true,
    mentionable: true,
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'video maker',
    color: Colors.Red,
    unicodeEmoji: ':clapper:',
    hoist: true,
    mentionable: true,
    room: ['Artist'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'movie buff',
    color: Colors.DarkPurple,
    unicodeEmoji: ':clapper:',
    hoist: true,
    mentionable: true,
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'athlete',
    color: Colors.Orange,
    unicodeEmoji: ':sports_medal:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  // gaming roles

  {
    name: 'Gaming',
    color: Colors.Red,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'minecraft player',
    color: Colors.Red,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'fps player',
    color: Colors.Blue,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'fifa player',
    color: Colors.Green,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'monster hunter player',
    color: Colors.Orange,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'pokemon player',
    color: Colors.Yellow,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'strategy player',
    color: Colors.Purple,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'pvp player',
    color: Colors.Red,
    unicodeEmoji: ':video_game:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'chess player',
    color: Colors.White,
    unicodeEmoji: ':chess_pawn:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'poker player',
    color: Colors.Green,
    unicodeEmoji: ':spades:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'sudoku player',
    color: Colors.Blue,
    unicodeEmoji: ':pencil2:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'scrabble player',
    color: Colors.Yellow,
    unicodeEmoji: ':abc:',
    hoist: true,
    mentionable: true,
    room: ['Gaming'],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  //  sexes role s

  {
    name: 'Male',
    color: Colors.Blue,
    unicodeEmoji: ':male_sign:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },

  {
    name: 'female',
    color: Colors.DarkVividPink,
    unicodeEmoji: ':female_sign:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: false,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'LGBT',
    color: Colors.DarkPurple,
    unicodeEmoji: ':rainbow_flag:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: true,
    haveAccessAllVoiceChanel: false,
  },
  {
    name: 'see-all-vices-chanels',
    color: Colors.DarkBlue,
    unicodeEmoji: ':fire:',
    hoist: true,
    mentionable: true,
    room: [],
    hasCategory: false,
    haveAccessAllVoiceChanel: true,
  },
];

export const categories = [
  {
    name: 'General',
    allowViewChanel: ['Male', 'female', 'LGBT'],
    denyViewChanel: ['@everyone'],
  },

  ...languagesRoles
    .filter((role) => !!role.hasCategory)
    .map((role) => {
      return {
        name: role.name,
        allowViewChanel: [
          ...languagesRoles
            .filter((languageRole) => {
              return (
                !!languageRole?.haveAccessAllVoiceChanel ||
                (languageRole.room ?? []).includes(role.name)
              );
            })
            ?.map((role) => role.name),
          role.name,
        ],
        denyViewChanel: ['@everyone'],
      };
    }),
];
